### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by bruab** [nynhle/competitive_scraper#5]
Come up with a *minimal* web page that you can serve locally and crawl, writing relevant output to a plain text file. Then you can change the page, crawl it again and have your program detect the change. Voila! Version 0.001!

**Comment by nynhle** [comment]
Pretty much done now. The comparer is tested on 'first_version.html' and 'second_version.html' in the testpages folder and changes are outputted in a log file. More work exactly how to store the changes and to make the user experience more neat is upcoming.
