### ISSUE TITLE
Stop importing sets module

### ISSUE THREAD

**Issue by bruab** [nynhle/competitive_scraper#6]
It's deprecated. The builtin `set()` function call takes its place with no import required (note lowercase).

https://www.python.org/dev/peps/pep-0004/
https://docs.python.org/2/library/stdtypes.html#set-types-set-frozenset

**Comment by nynhle** [comment]
Thanks for pointing that out! Fixed now.

**Comment by nynhle** [comment]
See the data_grabbing branch for update.
